### ISSUE TITLE
Ignoring HTML5 form validation

### ISSUE THREAD

**Issue by Xesher** [biscolab/laravel-recaptcha#10]
if the input field is empty, the submit event handler doesn't run. It will be triggered only if the HTML5 validation (the required attribute, in this case) has passed.

I'd expect a captcha to run after the HTML5 validation too; why do I have to annoy the user compiling a captcha if later on I'd warn him there are missing fields ? First I should force the user to do everything in the right way, then ensure it's a human and not a bot, IMHO.

Appearently, reCaptcha does something on the form it attaches on, removing the HTML5 validation feature.

The form will be submitted with the empty field, without notifying the user about its obligatoriness.

Any clue on why it acts like this ? Is there a way I can instruct reCaptcha to let HTML5 form validation run before taking control ?

**Comment by biscolab** [comment]
The ReCaptcha is a further mandatory field, it does not replace HTML validation. The standard HTML validation can be handled via HTML code. You can find more information about HTML 5 validation at this page: [https://www.w3.org/TR/html5/sec-forms.html#element-attrdef-form-novalidate](https://www.w3.org/TR/html5/sec-forms.html#element-attrdef-form-novalidate).

**Comment by akmalelias** [comment]
Hi @biscolab, since its quite related with this topic/question, may I know how to make the laravel-recaptcha is required before submitting the form? Thanks in advance.

**Comment by desthercz** [comment]
@biscolab I dont know, in my case it completely bypasses html validation and just submit form right away.

**Comment by AndrewSavetchuk** [comment]
@desthercz Yeah, same here... HTML validation is not working at all.
