### ISSUE TITLE
do it work with php 7 ?

### ISSUE THREAD

**Issue by vahidalvandi** [biscolab/laravel-recaptcha#12]
do it work with php 7 ?

**Comment by biscolab** [comment]
Version 3.x doesn't work with php 7.0. I suggest you try [v2.0.4](https://github.com/biscolab/laravel-recaptcha/tree/v2.0.4) BUT I'm honest, I've never tried it with php 7

**Comment by vahidalvandi** [comment]
please add support in php 7

**Comment by ametad** [comment]
@vahidalvandi Perhaps you overlooked, but this package does support PHP 7.1. That is also the major version 7. Does this meet your needs after all?
