### ISSUE TITLE
Route Caching Error Due to Closure

### ISSUE THREAD

**Issue by paulredmond** [biscolab/laravel-recaptcha#17]
A recent update added a closure route, which makes my route:cache fail during `php artisan route:cache`:

![image](https://user-images.githubusercontent.com/177773/52231343-eb460f80-2876-11e9-9900-e6ced0131c69.png).

I am thankful that the package allows me to configure my own route path so I can define my own controller, however, I think it would be advisable to convert this to a controller.

**Comment by biscolab** [comment]
@paulredmond, ReCaptchaController@validateV3 action is now associated to biscolab-recaptcha/validate route. 
Running `php artisan route:cache` everything works fine. 
Commit [67fb51], release v3.3.0
