### ISSUE TITLE
validateV3() must be of type array, boolean returned

### ISSUE THREAD

**Issue by michaelnguyen2021** [biscolab/laravel-recaptcha#19]
**Describe the bug**
This error does not happen all the time. It has been less than 1% in all page load. Sometime, when a recaptcha v3 enabled page is loaded, there is an error reported in sentry.io and the error is Return value of Biscolab\ReCaptcha\Controllers\ReCaptchaController::validateV3() must be of the type array, boolean returned.

The error stack is below:

```
Symfony\Component\Debug\Exception\FatalThrowableError: Return value of Biscolab\ReCaptcha\Controllers\ReCaptchaController::validateV3() must be of the type array, boolean returned
#54 vendor/biscolab/laravel-recaptcha/src/Controllers/ReCaptchaController.php(27): validateV3
#53 vendor/biscolab/laravel-recaptcha/src/Controllers/ReCaptchaController.php(0): call_user_func_array
```

**To Reproduce**
1. Follow exact instruction to install recaptcha V3
2. open the page with recaptcha V3 enabled
3. See the error reported

**Expected behavior**
Error should not happen

**Screenshots**

**Environment:**
Homestead
Laravel 5.7.20

**Additional context**
n/a

**Comment by biscolab** [comment]
Thanks @michaelnguyen547. I'll fix it ASAP

**Comment by biscolab** [comment]
Fixed in v3.4.0 131b915

**Comment by jfvoliveira** [comment]
Sorry to be opening this but I keep having this same error `Return value of Biscolab\ReCaptcha\Controllers\ReCaptchaController::validateV3() must be of the type array, bool returned`
I am using ReCaptcha v2.

From what I can tell, the mentioned method has the `: array` return type and it calls the `return recaptcha()->validate($token);` method that has some paths returing true or false. I think that may be the issue.

`"biscolab/laravel-recaptcha": "^4.4",`
`"laravel/framework": "^7.0",`

Thanks

**Comment by biscolab** [comment]
Hi @jfvoliveira, if you are using ReCaptcha v2, there are obviously errors when you call `ReCaptchaController::validateV3()` and, indeed, you shouldn't use that route. You cannot use V2 and V3 at the same time.
Please. next time follow the issue template.
