### ISSUE TITLE
Javascript callback function for v2

### ISSUE THREAD

**Issue by tuyenlaptrinh** [biscolab/laravel-recaptcha#25]
I used this code
```
<form action="" method="post">
        @csrf
        {!! htmlFormSnippet() !!}
        <input type="submit" value="Click here to continue" id="submit_form" disabled>
    </form>
```
and
```
htmlScriptTagJsApi()
```
I want to add javascript call back function to valid form and enable that button.
But I could not find any solution
I think this is new sugesstion. Thanks

**Comment by biscolab** [comment]
Hi @tuyenlaptrinh , in the next release you'll find a lot of new features. You'll be able to add  callback functions and several "data" attributes to customize your captcha.

**Comment by biscolab** [comment]
Project "v4" : https://github.com/biscolab/laravel-recaptcha/projects/3#card-25978736
