### ISSUE TITLE
Set language for ReCAPTCHA v2 Checkbox

### ISSUE THREAD

**Issue by lavapi** [biscolab/laravel-recaptcha#27]
As you wrote $configuration argument can have following keys:
`{!! htmlScriptTagJsApi(['lang' => 'en' !!}` , but it does not work. As I checked you need to pass `{!! htmlScriptTagJsApi(['resources' => 'en' !!}` instead. Please check if I am right.

**Comment by biscolab** [comment]
@lavapi I'm fixing

**Comment by lavapi** [comment]
great

**Comment by biscolab** [comment]
@lavapi update to v4.0.1
