### ISSUE TITLE
Uncaught (in promise) Timeout

### ISSUE THREAD

**Issue by emperorjm** [biscolab/laravel-recaptcha#28]
I am using Laravel v5.6 and Laravel Recaptcha version 3.6.

I have a customer login page and an admin login page. I added the recaptcha to both and it works on the customer login page but when I click the checkbox on the admin login page I keep getting this **"Uncaught (in promise) Timeout"** error where the widget spins and then it goes back to the default unchecked state and therefore I am unable to log in.

**Comment by biscolab** [comment]
Hi @emperorjm it looks like a JS issue. Could you please give more details about your login page?

**Comment by emperorjm** [comment]
It worked a few times after my post above but majority of the time I got the timeout error. I had to disable the plugin for the admin login page due to urgent issues but will test it again and give you some more details in the hopes of helping to fix the issue.

**Comment by biscolab** [comment]
@emperorjm as I've already told you, I need more details like either the exact error message or at least a screenshot of your browser console.
