### ISSUE TITLE
how can i show the validator error in the view

### ISSUE THREAD

**Issue by danielshongo** [biscolab/laravel-recaptcha#29]
thank you brother for this package
that is my code
@error('g-recaptcha-respons')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror

**Comment by biscolab** [comment]
@danielshongo there are several ways to display errors: [https://laravel.com/docs/5.8/validation#quick-displaying-the-validation-errors](https://laravel.com/docs/5.8/validation#quick-displaying-the-validation-errors)
