### ISSUE TITLE
Feature Request: Badge Configuration

### ISSUE THREAD

**Issue by warkior** [biscolab/laravel-recaptcha#30]
I was just wondering if it is possible to configure where the badge shows up on the page. We are using the Invisible captcha, and it shows the small Google badge in the bottom right corner. We also have another JS tool that displays a badge in the same corner. 

Looks like it is possible to adjust the badge location in the Google docs, but I'm not sure if it is possible to use these settings in the Laravel configuration.
See data-badge on this page...
https://developers.google.com/recaptcha/docs/invisible

Thanks in advance!

**Comment by biscolab** [comment]
Hi @warkior, you can set `data-badge` tag attribute calling `htmlFormButton` helper:
```blade
{!! htmlFormButton("Submit", [
// Other properties
    'data-badge' => 'bottomleft' // default is 'bottomright', 'inline' lets you position it with CSS.
]) !!}
```

I'll work to improve invisible `g-recaptcha` tag attributes in the next release.

**Comment by bayanbts** [comment]
@biscolab I try to add the code you added above but i am getting the error :
Call to undefined method Biscolab\ReCaptcha\ReCaptchaBuilderV3::htmlFormButton()
