### ISSUE TITLE
Documentation site not working

### ISSUE THREAD

**Issue by davefv** [biscolab/laravel-recaptcha#33]
Hi!

I'm trying to get the documentation at [https://laravel-recaptcha-docs.biscolab.com/docs/intro](https://laravel-recaptcha-docs.biscolab.com/docs/intro) but page is not working.

The response is:
Error 526 Invalid SSL Certificate

Thank you for your amazing job!

**Comment by biscolab** [comment]
Thanks @davefv , I made mistake in ssl settings
