### ISSUE TITLE
Laravel 7.x Support

### ISSUE THREAD

**Issue by vbasky** [biscolab/laravel-recaptcha#38]
Unable to upgrade to Laravel 7.x

Problem 1
    - Conclusion: remove biscolab/laravel-recaptcha 4.0.1
    - Conclusion: don't install biscolab/laravel-recaptcha 4.0.1
    - Conclusion: don't install laravel/framework v7.0.2

**Environment:**
 - OS and server: Mac OS Catalina 
 - PHP version [7.3.14]
 - Laravel version [e.g. 6.18.0]
 - Package version [e.g. 3.4.1]

**Comment by biscolab** [comment]
@vbasky as you can read from README file and documentation, version 4.0.1 is not compatible with Laravel 7. AFAIK, It should be already compatible but, honestly, I don't have yet read Laravel 7 doc and changelog. I'm testing right now and I' ll release a new package version for Laravel 7 ASAP.

**Comment by vbasky** [comment]
Thanks for quickly fixing, yes I realised it wasn't compatible in the README. However this is no way to distinguish in an github issue between a defect and compatibility request.
