### ISSUE TITLE
Disable button after click

### ISSUE THREAD

**Issue by pflirae** [biscolab/laravel-recaptcha#39]
**Describe Missing Feature**
Not possible to disable the button after it is clicked.

**To Reproduce**
I want to disable the button after it is clicked, since some users click many times the button, currentlly the button remains enabled after the click.

**Expected behavior**
After click the button is disabled.

**Environment:**
Not browser dependent.

**Possible Solution**
On htmlScriptTagJsApi, add an additional propertie like :
'disable' => true, so the button is disabled after click or false if the button should remain enabled.

**Comment by biscolab** [comment]
Hi @pflirae, AFAIK the button changes its status by itself after clicked...thereafter even you click several times on the button nothing will happen.
Could you explain it better?
Thanks
