### ISSUE TITLE
Call to undefined method Biscolab\ReCaptcha\ReCaptchaBuilderV2::htmlFormButton()

### ISSUE THREAD

**Issue by jafarchoupan** [biscolab/laravel-recaptcha#40]
**Environment:**
 - OS and server: [e.g. Ubuntu 16.04 / Nginx] (If you are using a VM on Windows DON'T "say" Windows)
 - PHP version [7.2.x]
 - Laravel version [7.0.4]
 - Package version [4.1]
you just write package i think you never test this code every version

**Comment by biscolab** [comment]
Hi @jafarchoupan...I' m afraid you missed something in your configuration.
I' ve just tested, for the umpteenth time, with a fresh Laravel 7 installation (laravel/laravel v7.3.0) and Laravel ReCaptcha package (biscolab/laravel-recaptcha v4.1.0).
Following steps as explained in https://laravel-recaptcha-docs.biscolab.com/docs/configuration and https://laravel-recaptcha-docs.biscolab.com/docs/how-to-use-v2.
PHP version is 7.3.9. Everything looks good.

> Why do you write "never test this code every version"? 
`htmlFormButton` is tested several times in `/tests/ReCaptchaHelpersInvisibleTest.php` and `/tests/ReCaptchaTest.php`

Please, check your `config/recaptcha.php` and make sure to set `version` as `invisible`, then it should work fine
