### ISSUE TITLE
Unresolvable dependency resolving [Parameter #0 [ <required> string $api_site_key ]] in class Biscolab\\ReCaptcha\\ReCaptchaBuilderInvisible

### ISSUE THREAD

**Issue by Klein-s** [biscolab/laravel-recaptcha#41]
![image](https://user-images.githubusercontent.com/63279751/82427817-2eec7900-9abc-11ea-9fc0-ac582379fb34.png)
There is a key in the configuration environment

**Comment by biscolab** [comment]
@QinJiu-one please follow [installation guidelines](https://laravel-recaptcha-docs.biscolab.com/docs/intro) and first of all [Bug report template](https://github.com/biscolab/laravel-recaptcha/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)...I need more details to help you. Thanks

**Comment by biscolab** [comment]
Due to inactivity
