### ISSUE TITLE
deferred rendering

### ISSUE THREAD

**Issue by shad0matic** [biscolab/laravel-recaptcha#42]
Hi,

I'm trying to defer rendering because recaptcha isn't visible at first on my page,
I did set "explicit" to true in the config as mentioned in the doc,
but I can't find where to add the name for my onload callback,
could you please provide an example for this (and add it in the doc) ?

Best regards,

Olivier

**Comment by biscolab** [comment]
@shad0matic I completely forgot to mention `biscolabOnloadCallback` function in my documentation. That is the default function name passed to `https://www.google.com/recaptcha/api.js` when `explicit` is set to `true`. can become customizable in next release.

**Comment by biscolab** [comment]
I also added it to the documentation page: [configuration](https://laravel-recaptcha-docs.biscolab.com/docs/configuration).
However, I'm planning to make that function name customizable in one of the next releases.
