### ISSUE TITLE
Adding reCaptch to Login

### ISSUE THREAD

**Issue by helderneves91** [biscolab/laravel-recaptcha#44]
Hello, this is not a bug.

I have implemented this package on a study project. I'm able to get keys from google, but how do I make the laravel login to validate de reCaptcha without messing with files in vendor folder?

I'm posting this because if I don't configure the proper domain, the login is successfull anyway. 

Regards

**Comment by biscolab** [comment]
User login is handled by `App\Http\Controllers\Auth\LoginController@login`. This method calls `validateLogin` method supplied by `AuthenticatesUsers` trait. To add recaptcha to the login form you have to override `validateLogin` method in `LoginController`
