### ISSUE TITLE
Call to undefined function htmlScriptTagJsApiV3()

### ISSUE THREAD

**Issue by hexpit** [biscolab/laravel-recaptcha#49]
**Describe the bug**
I am getting the same error from issue#22. I am already using v4.12 but still getting Call to undefined function htmlScriptTagJsApiV3() error on my blade file.

**Comment by biscolab** [comment]
Hi @hexpit, I can't help you without details about your configuration. Please follow [Issue template](https://github.com/biscolab/laravel-recaptcha/blob/master/.github/ISSUE_TEMPLATE/bug_report.md), check the actual version you have installed, and read [documentation](https://laravel-recaptcha-docs.biscolab.com/docs/how-to-use-v3)
