### ISSUE TITLE
Data-Callback overwriting

### ISSUE THREAD

**Issue by koderis-volkovs** [biscolab/laravel-recaptcha#55]
**Describe the bug**
When I use invisible captcha, it's not possible to overwrite `data-callback`

`{!! htmlFormButton(trans('contact.send_button'), ['class' => 'btn submit', 'data-badge' => 'bottomleft', 'data-callback' => 'myCustomFunction']) !!}`

<img width="281" alt="Screen Shot 2021-01-14 at 11 02 34" src="https://user-images.githubusercontent.com/45522858/104568126-55b57c00-5658-11eb-811d-8b0c04c5ae79.png">

**Expected behavior**
`data-callback` attribute must be overwritten to `myCustomFunction`

**Environment:**
 - PHP version 7.4.11
 - Laravel version 8.19.0
 - Package version 5.0

**Comment by koderis-volkovs** [comment]
Probably
```
$properties = array_merge($properties, [
    'data-sitekey'  => $this->api_site_key,
    'data-callback' => 'biscolabLaravelReCaptcha'
]);
```
should be changed to 
```
$properties = array_merge($properties, [
    'data-sitekey'  => $this->api_site_key,
    'data-callback' => $properties['data-callback']' ?? biscolabLaravelReCaptcha',
]);
```

**Comment by biscolab** [comment]
Hi @koderis-volkovs, thanks for your feedback. I've some doubts about your Laravel and PHP versions (Laravel's last release is currently 8.5.8...and it would require at least PHP 7.3). However, I'll check for this bug

**Comment by koderis-volkovs** [comment]
> ld require at least PHP 7.3). Howev

Sorry, fixed versions. What's possible ETA ?
