### ISSUE TITLE
Currently it is not possible to update while using php 8

### ISSUE THREAD

**Issue by eric2100** [biscolab/laravel-recaptcha#56]
Problem 2
    - Root composer.json requires biscolab/laravel-recaptcha ^4.4 -> satisfiable by biscolab/laravel-recaptcha[4.4.0].
    - biscolab/laravel-recaptcha 4.4.0 requires php ^7.1 -> your php version (8.0.2) does not satisfy that requirement.

**Comment by biscolab** [comment]
@eric2100 use biscolab/laravel-recaptcha 5
