### ISSUE TITLE
Call to undefined method Biscolab\ReCaptcha\ReCaptchaBuilderV2::htmlFormButton()

### ISSUE THREAD

**Issue by byGits** [biscolab/laravel-recaptcha#62]
**Describe the bug**
Hi, thanks for the package, unfortunately I get the following error:
`Call to undefined method Biscolab\ReCaptcha\ReCaptchaBuilderV2::htmlFormButton()`

When I remove `{!! htmlFormButton() !!}` the captcha appears correctly (without the submit button obviously).

Configs are set too, both in .env and recaptcha.php file.

I also tried `{!! ReCaptcha::htmlFormButton() !!}` and still the same, I'm using v2 but even if I change it to invisible in config, then I get this error instead: `Call to undefined method Biscolab\ReCaptcha\ReCaptchaBuilderInvisible::htmlFormSnippet()`

**Environment:**
 - OS and server: Mac
 - PHP version 8.0.8
 - Laravel version 8.66.0
 - Package version 5.0.1

**Comment by biscolab** [comment]
@byGits please check your configuration and follow instructions you can find at [https://laravel-recaptcha-docs.biscolab.com/docs/how-to-use-v2](https://laravel-recaptcha-docs.biscolab.com/docs/how-to-use-v2):
- `htmlFormButton` works only with "V2 Invisible"
- `htmlFormSnippet` works only with "V2 Checkbox"
