### ISSUE TITLE
Laravel Nova is always in English when using this package

### ISSUE THREAD

**Issue by lisotton** [biscolab/laravel-recaptcha#63]
**Describe the bug**
I have an installation of Laravel Nova in the same app that I'm using this package and I noticed that Laravel Nova started to be in English after installing this package. I have the translations for Laravel Nova to Brazilian Portuguese. 

**To Reproduce**
1. Install Laravel Nova (hard to reproduce because needs a license)
2. Change the app to a different language
3. Create some translations for this new language
4. Install this package
5. Go to Nova installation and you will see that Laravel Nova is in English

**Expected behavior**
See Laravel Nova in configured language.

**Screenshots**
When this package is installed:
![image](https://user-images.githubusercontent.com/1653860/139455948-48070cc1-7318-4fac-8efc-8e90becc366b.png)

If I comment this line in `ReCaptchaServiceProvider`:
![image](https://user-images.githubusercontent.com/1653860/139456048-951fc49b-4eb2-4482-b26e-8a5d0f6d1692.png)

Then I have it in the correct language:
![image](https://user-images.githubusercontent.com/1653860/139456158-f2aa9f4e-adcd-4df0-b3d5-d3acb3a22833.png)

**Environment:**
 - OS and server: Docker image php8.0-apache
 - PHP version 8.0
 - Laravel version 8.68.1
 - Package version 5.0.1

**Comment by biscolab** [comment]
As I explained I can't merge your pull request but I'm on it

**Comment by lisotton** [comment]
If you need any other info or help to reproduce, I'm available.

**Comment by biscolab** [comment]
I read Nova documentation [https://nova.laravel.com/docs/3.0/customization/localization.html](https://nova.laravel.com/docs/3.0/customization/localization.html) and Nova issue tracker [https://github.com/laravel/nova-issues/issues/2774](https://github.com/laravel/nova-issues/issues/2774). It seems that Nova only works with JSON translation files. It could be a good starting point. I'll keep you posted.

**Comment by lisotton** [comment]
I'm not sure if this is the case, I'm already using JSON translation files for Nova.

**Comment by biscolab** [comment]
@lisotton please update to v5.1.0 and add `'empty_message' => true,` to the `recaptcha.php` config file. Please give me feedback.
