### ISSUE TITLE
Documentation Site Returns 404

### ISSUE THREAD

**Issue by mostafaznv** [biscolab/laravel-recaptcha#78]
I wanted to use this package but documentation page doesn't work. it returns 404 error

**To Reproduce**
1. Go to https://laravel-recaptcha-docs.biscolab.com
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/7619687/184554922-b1cba697-c858-49c8-bf7f-54f6b40f4c61.png)

**Comment by UsaidMuhammad** [comment]
you can use this web archive link for now, until the author brings it back up.

https://web.archive.org/web/20211022210332/https://laravel-recaptcha-docs.biscolab.com/docs/intro

**Comment by biscolab** [comment]
@mostafaznv I moved the entire documentation to the README file: https://github.com/biscolab/laravel-recaptcha
