### ISSUE TITLE
Laravel-recaptcha doesn't support Laravel 10

### ISSUE THREAD

**Issue by lopatin96** [biscolab/laravel-recaptcha#85]
I really love laravel-recaptcha and it was working in Laravel 9, but now there is a new version of Laravel, so I am blocked and can't update the whole project, could you please add a support of Laravel 10?

Thank you in advance!

**Comment by biscolab** [comment]
I'm sorry about the documentation I didn't update, but I released 2 weeks ago the Laravel 10 support
