### ISSUE TITLE
upgrade laravel eror

### ISSUE THREAD

**Issue by hidessh99** [biscolab/laravel-recaptcha#87]
i upgrade laravel 9 to laravel 10 

i found bug
    - biscolab/laravel-recaptcha[5.0.0, ..., 5.2.0] require laravel/framework ^7.0|^8.0 -> found laravel/framework[v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but it conflicts with your root composer.json require (^10.0).

how to fix ????

**Comment by krit0627** [comment]
Me too. 👍

**Comment by camerontucker** [comment]
In composer.json change to ^6.0.

"biscolab/laravel-recaptcha": "^5.0" -> "biscolab/laravel-recaptcha": "^6.0"

**Comment by biscolab** [comment]
Thanks @camerontucker. @hidessh99 and @krit0627 please remember to update `biscolab/laravel-recaptcha` to the version "6" as well!
