### ISSUE TITLE
not working with invisble

### ISSUE THREAD

**Issue by Sarfroz** [biscolab/laravel-recaptcha#9]
hi , everttime i try to submit the form i get  Hey!!! Recaptcha is wrong!
i am using laravel 5.6
i also added this:

<script src='https://www.google.com/recaptcha/api.js' async defer></script><script>
--
  | function biscolabLaravelReCaptcha(token) {
  | document.getElementById("login-form").submit();
  | }
  | </script>
 {!! htmlFormButton() !!}

**Comment by biscolab** [comment]
Hi, I tried the "invisible version" and it works. Please check following steps:

- set "version" => "invisible" in config/recaptcha.php 

- set "form-id" as parameter of `htmlScriptTagJsApi`: `{!! htmlScriptTagJsApi("form-id") !!}`

- set HTML form id property `<form id="form-id">`

It should works properly.

**Comment by biscolab** [comment]
I will improve the documentation
